// Code generated by wit-bindgen-go. DO NOT EDIT.

package helloworld

// Exports represents the caller-defined exports from "enclave:examples-go/hello-world".
var Exports struct {
	// Hello represents the caller-defined, exported function "hello".
	//
	//	hello: func() -> tuple<string, string>
	Hello func() (result [2]string)

	// Google represents the caller-defined, exported function "google".
	//
	//	google: func() -> tuple<string, string>
	Google func() (result [2]string)

	// Greet represents the caller-defined, exported function "greet".
	//
	//	greet: func(name: string) -> tuple<string, string>
	Greet func(name string) (result [2]string)

	// PrintEnv represents the caller-defined, exported function "print-env".
	//
	//	print-env: func() -> tuple<string, string>
	PrintEnv func() (result [2]string)

	// PrintArgs represents the caller-defined, exported function "print-args".
	//
	//	print-args: func() -> tuple<string, string>
	PrintArgs func() (result [2]string)
}
