// Code generated by wit-bindgen-go. DO NOT EDIT.

package helloworld

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "enclave:examples-go".

//go:wasmexport enclave:examples-go/hello-world#hello
//export enclave:examples-go/hello-world#hello
func wasmexport_Hello() (result *[2]string) {
	result_ := Exports.Hello()
	result = &result_
	return
}

//go:wasmexport enclave:examples-go/hello-world#google
//export enclave:examples-go/hello-world#google
func wasmexport_Google() (result *[2]string) {
	result_ := Exports.Google()
	result = &result_
	return
}

//go:wasmexport enclave:examples-go/hello-world#greet
//export enclave:examples-go/hello-world#greet
func wasmexport_Greet(name0 *uint8, name1 uint32) (result *[2]string) {
	name := cm.LiftString[string]((*uint8)(name0), (uint32)(name1))
	result_ := Exports.Greet(name)
	result = &result_
	return
}

//go:wasmexport enclave:examples-go/hello-world#print-env
//export enclave:examples-go/hello-world#print-env
func wasmexport_PrintEnv() (result *[2]string) {
	result_ := Exports.PrintEnv()
	result = &result_
	return
}

//go:wasmexport enclave:examples-go/hello-world#print-args
//export enclave:examples-go/hello-world#print-args
func wasmexport_PrintArgs() (result *[2]string) {
	result_ := Exports.PrintArgs()
	result = &result_
	return
}
